import * as LanguageToStudentAPIUtil from '../util/language_to_student_api_util';

export const RECEIVE_ALL_LANGUAGE_TO_STUDENTS = 'RECEIVE_ALL_LANGUAGE_TO_STUDENTS';
export const RECEIVE_LANGUAGE_TO_STUDENT = 'RECEIVE_LANGUAGE_TO_STUDENT';
export const REMOVE_LANGUAGE_TO_STUDENT = 'REMOVE_LANGUAGE_TO_STUDENT';